### PR TITLE
Igraph fix, moe -> neimode

### PR DESCRIPTION
**Pull request by alexanderbates**

### CODE REVIEW

**Comment by alexanderbates** [comment]
Ah sorry, accidentally committed a lot of very old changes. Only meant for 60237e5.

**Review by jefferis — CHANGES_REQUESTED** [review]
Hi @alexanderbates, thanks for PR but I think something is not quite right here.
1. neimode has been replace by mode (see #496) and your change is attempting to reverse that.
2. you are on a stale branch
I assume that you have an old version of igraph installed since they told us that mode had been the preferred argument for some time now. I guess the correct thing to do is to put a minimum version on igraph. @dokato do you know what that is?

**Comment by alexanderbates** [comment]
Ah the problem was that I was having difficulty compiling igraph from source

**Comment by jefferis** [comment]
Hmm, I looked and it seems that this switch in argument name happened quite suddenly from one version to the next. We could make it's use conditional on version but that's a bit of a pain.

**Pull request closed without merging**
