### PR TITLE
Change rgl.* calls to *3d

### PR DESCRIPTION
**Pull request by dmurdoch**
Some upcoming changes to the rgl package will require changes to nat. 
I will be deprecating a number of rgl.* function calls.  You can read 
about the issues here:

   https://dmurdoch.github.io/rgl/articles/deprecation.html

I have made the required changes in the attached patches.  

Duncan Murdoch

### CODE REVIEW

**Comment by jefferis** [comment]
Dear @dmurdoch, many thanks for this. Do we need to change e.g.

https://github.com/natverse/nat/blob/master/R/neuronlist_interactive_3d.R#L197-L198

as well?

**Comment by dmurdoch** [comment]
`rgl.pop` is not being deprecated because it is identical to `pop3d`.  I've generally been suggesting that change because `rgl.pop` won't show up in the help index for `rgl`, but you won't get warnings or errors for it.  Not sure why I didn't do it in this PR.  Been sending out a lot of them...

**Comment by jefferis** [comment]
Thanks for clarifying! If you looked for someting `rgl.pop(` you wouldn't find this as I used sapply here.

**Comment by jefferis** [comment]
remaining errors seem to be due to old versions of alphashape3d

**Comment by jefferis** [comment]
Thanks for the PR @dmurdoch. I will be submitting an update to CRAN shortly.

**Pull request merged**
