### PR TITLE
GitHub actions with coveralls

### PR DESCRIPTION
**Pull request by dokato**
Related to #450.

I had a quick try on github actions, I can't quite figure out why Windows CMTK installation fails...
I also temporarily switched of ubuntu release as it was taking forever to pull down dependencies. This should work no problem though.
If we want to get unblock for now, I suggest testing on mac/ubuntu now and figure the rest later?

### CODE REVIEW

**Comment by dokato** [comment]
Also @jefferis I need a bit more info on what `travisbuildchildren.sh` supposed to do?

**Comment by jefferis** [comment]
Thanks so much @dokato. I would like to merge quickly, but just wanted to check re coverage. I have been using coveralls for status (there is a badge) but not as a CI check. Were you suggesting a codecov CI check? This might be good.

Also could you summarise the windows issues? I did not have a Windows build in the past, but it might be nice to add one.

**Comment by dokato** [comment]
> Were you suggesting a codecov CI check? This might be good.

Ah, force of habit. I used in previous projects codecov mainly. I can change to coveralls, no problem.

With windows the error comes from installing CMTK. The excerpt from logs is below.

```
CMake Error at Utilities/numdiff-5.2.1/CMakeLists.txt:155 (MESSAGE):
  Declaration of vsprintf() not present!
```

You can see the whole logs [here](https://github.com/dokato/nat/runs/3030137444?check_suite_focus=true#step:8:581).
I wasn't sure if there's an easy way to install from `exe` using windows command line.

BTW I checked also curls from `travisbuildchildren.sh`, they seem not to work now. Do we need some replacement here too?

**Comment by dokato** [comment]
@jefferis I had a first go with coveralls, looks like we need to have `COVERALLS_TOKEN` set up: https://github.com/r-lib/covr#coveralls. It probably wasn't needed for travis.

Now it failed:
```
Error in covr::coveralls() : 
  Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.
```

**Comment by jefferis** [comment]
@dokato, I added the COVERALLS_TOKEN as a secret and reran the jobs, but that still failed. I forgot, but I think it needs to be exposed explicitly in the workflow doc.

**Comment by jefferis** [comment]
This is really frustrating re coveralls. The best lead I have found is [here](https://github.com/r-lib/covr/issues/457). But I think we should already be fulfilling everything that he says.

**Comment by dokato** [comment]
Thanks @jefferis, actually just before lunch I found this thread with your comments from April ;) I'm testing 2 more things from this user advice. If that doesn't work, are you happy to migrate to codecov?

**Comment by jefferis** [comment]
>  If that doesn't work, are you happy to migrate to codecov?
Sure. I do have a lot of coverage history but the end of the day we're mostly interested in current state and the next delta.

**Comment by dokato** [comment]
Before I do that, are you sure @jefferis that the coveralls repo token is correctly set up as secret? I tested on my repo (`todor`) locally and with GA and it worked just fine: https://github.com/dokato/todor/runs/3036482539?check_suite_focus=true#step:12:14
I.e.
```
> Rscript -e 'covr::coveralls(service_name="jenkins")' 
$message
[1] "Job ##3.1"

$url
[1] "https://coveralls.io/jobs/83379076"
```

Could you share with me this code through some vault? I don't have privilidges for nat to see it [here](https://coveralls.io/github/natverse/nat).

**Comment by jefferis** [comment]
Thanks for all of this @dokato. As you can see I have just gone with your codecov branch – not worth going against the current for something not mission critical!

**Pull request closed without merging**
