### PR TITLE
[add] print method for neuronlistz

### PR DESCRIPTION
**Pull request by dokato**
Addresses #466 .

I simplified so it doesn't call expensive `contents.classes <- sapply(x, firstclass, USE.NAMES = F)`.

Artefact, we don't print the information about neuron types.

```r
> nzmv
'neuronlistz' containing 3000 neurons objects and 'data.frame' with 1 vars [998 kB]
```

Benchmark on 3000 neurons:

```r
# old
> system.time(print(nzmv))
'neuronlistz' containing 3000 'neuprintneuron' objects and 'data.frame' with 1 vars [998 kB]
   user  system elapsed 
 16.702   1.805  19.000 
# new
> system.time(print(nzmv))
'neuronlistz' containing 3000 neurons objects and 'data.frame' with 1 vars [998 kB]
   user  system elapsed 
  0.000   0.000   0.001 
```

Alternatively, we can add another rds that stores that info in zip? WDYT @jefferis ?

### CODE REVIEW

**Comment by jefferis** [comment]
Thanks @dokato. This is good, but can you add the path to the zip file and its size on disk to the displayed information and make it clear that the currently printed size is just for the portion in memory?

**Comment by dokato** [comment]
Is message like this okay?
```
'neuronlistz' containing 3000 neurons objects and 'data.frame' with 1 vars.
Neurons loaded on demand from 'testz.zip' [93.1 MB]. Currently in memory: 998 kB.
```

**Comment by jefferis** [comment]
Thanks! How about:
```
'neuronlistz' containing 3000 neurons objects and 'data.frame' with 1 vars [998 kB in RAM].
Loaded on demand from '/x/y/z/testz.zip' [93.1 MB on disk].
```

**Comment by dokato** [comment]
Sure, done!

**Comment by jefferis** [comment]
Thanks again @dokato!

**Pull request merged**
