### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by alexanderbates**

### CODE REVIEW

**Comment by jefferis** [comment]
Thanks @alexanderbates!

I am working on this, so no need to update, but in future I recommend against re-running pkgdown on a feature branch like this.

1. you just intended to add a logo, but there are 218 changed files
2. there are conflicts with master because of changes on both side in the pkgdown docs

**Comment by alexanderbates** [comment]
Ah okay - do you want me to make a PR without the pkgdown stuff?

**Comment by jefferis** [comment]
No it's fine. I'm cleaning it up.

**Comment by alexanderbates** [comment]
Noted

**Pull request merged**
